/******************************************************************************
** Copyright (c) 2006-2023 Unified Automation GmbH All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** Project: .NET based OPC UA Client Server SDK
**
** Description: OPC Unified Architecture Software Development Kit.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
******************************************************************************/

#pragma warning disable 1591
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
//
namespace UnifiedAutomation.EventHistory {
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mycompany.com/EventHistorySchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("EventHistory", Namespace="http://mycompany.com/EventHistorySchema.xsd", IsNullable=false)]
    public partial class EventHistoryType {

        private string[] namespaceUriField;

        private SelectClauseType[] selectClauseField;

        private EventInstance[] eventField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NamespaceUri")]
        public string[] NamespaceUri {
            get {
                return this.namespaceUriField;
            }
            set {
                this.namespaceUriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SelectClause")]
        public SelectClauseType[] SelectClause {
            get {
                return this.selectClauseField;
            }
            set {
                this.selectClauseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Event")]
        public EventInstance[] Event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mycompany.com/EventHistorySchema.xsd")]
    public partial class SelectClauseType {

        private string eventTypeIdField;

        private string dataTypeIdField;

        private int valueRankField;

        private string valueField;

        public SelectClauseType() {
            this.eventTypeIdField = "i=2041";
            this.dataTypeIdField = "i=24";
            this.valueRankField = -1;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("i=2041")]
        public string EventTypeId {
            get {
                return this.eventTypeIdField;
            }
            set {
                this.eventTypeIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("i=24")]
        public string DataTypeId {
            get {
                return this.dataTypeIdField;
            }
            set {
                this.dataTypeIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int ValueRank {
            get {
                return this.valueRankField;
            }
            set {
                this.valueRankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mycompany.com/EventHistorySchema.xsd")]
    public partial class EventInstance {

        private System.Xml.XmlElement[] fieldField;

        private uint timeField;

        private uint receiveTimeField;

        private byte[] eventIdField;

        private string eventTypeIdField;

        private string sourceNameField;

        private string sourceNodeField;

        private uint severityField;

        private string messageField;

        public EventInstance() {
            this.receiveTimeField = ((uint)(0));
            this.eventTypeIdField = "i=2041";
            this.sourceNameField = "Server";
            this.sourceNodeField = "i=2253";
            this.severityField = ((uint)(500));
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Field")]
        public System.Xml.XmlElement[] Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint ReceiveTime {
            get {
                return this.receiveTimeField;
            }
            set {
                this.receiveTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="base64Binary")]
        public byte[] EventId {
            get {
                return this.eventIdField;
            }
            set {
                this.eventIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("i=2041")]
        public string EventTypeId {
            get {
                return this.eventTypeIdField;
            }
            set {
                this.eventTypeIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Server")]
        public string SourceName {
            get {
                return this.sourceNameField;
            }
            set {
                this.sourceNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("i=2253")]
        public string SourceNode {
            get {
                return this.sourceNodeField;
            }
            set {
                this.sourceNodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "500")]
        public uint Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
}
